version: '3.4'

services:
  orleans_silohost:
    image: ${DOCKER_REGISTRY-}localconsolesilohost:${SILO_HOST_VER:-latest}
    build:
      context: .
      dockerfile: ServerSide/LocalConsoleSiloHost/Dockerfile
    volumes:
      - helloworld_grain_volume:/grains/helloworld_grain
      - myreminder_grain_volume:/grains/myreminder_grain
      - numbergenerator_grain_volume:/grains/numbergenerator_grain
    networks:
      - orlean_demo
    depends_on:
      - helloworld_grain
      - myreminder_grain
      - numbergenerator_grain
      - mongo_store

  helloworld_grain:
    image: ${DOCKER_REGISTRY-}helloworld_grain:${GRAIN_VER_HELLOWORLD:-latest}
    build:
      context: .
      dockerfile: ServerSide/Grains/HelloWorld.Grain/docker/Dockerfile
    volumes:
      - helloworld_grain_volume:/app_grain

  myreminder_grain:
    image: ${DOCKER_REGISTRY-}myreminder_grain:${GRAIN_VER_MYREMINDER:-latest}
    build:
      context: .
      dockerfile: ./ServerSide/Grains/MyReminder.Grain/docker/Dockerfile
    volumes:
      - myreminder_grain_volume:/app_grain

  numbergenerator_grain:
    image: ${DOCKER_REGISTRY-}numbergenerator_grain:${GRAIN_VER_NUMBERGENERATOR:-latest}
    build:
      context: .
      dockerfile: ./ServerSide/Grains/NumberGenerator.Grain/docker/Dockerfile
    volumes:
      - numbergenerator_grain_volume:/app_grain

  webclientdemo:
    image: ${DOCKER_REGISTRY-}webclientdemo:${WEB_CLIENT_VER:-latest}
    build:
      context: .
      dockerfile: ClientSide/WebClientDemo/Dockerfile
    networks:
      - orlean_demo
    depends_on: 
      - orleans_silohost
      - mongo_store
  
  mongo_store:
    image: mongo:4
    volumes:
      - mongo_store_volume:/data/db
    networks:
      - orlean_demo

networks:
  orlean_demo:

volumes:
  helloworld_grain_volume:
  myreminder_grain_volume:
  numbergenerator_grain_volume:
  mongo_store_volume:
