version: '3.7'

services: 
  console_silohost:
    image: ${DOCKER_REGISTRY-}localconsolesilohost:${SILO_HOST_VER:-latest}
    environment:
      - GrainLoadPath=/grains
      - ORLEANS_HOST_APP_Orleans__GrainOption__LoadPaths__0={GrainLoadPath}/helloworld_grain/HelloWorld.Grain.dll
      - ORLEANS_HOST_APP_Orleans__GrainOption__LoadPaths__1={GrainLoadPath}/myreminder_grain/MyReminder.Grain.dll
    volumes:
      - type: volume
        source: helloworld_grain_volume
        target: /grains/helloworld_grain
        read_only: true
      - type: volume
        source: myreminder_grain_volume
        target: /grains/myreminder_grain
        read_only: true
    networks:
      - orleans_virtual_network
    depends_on:
      - helloworld_grain
      - myreminder_grain
      - demo_mongo_store

  helloworld_grain:
    image: ${DOCKER_REGISTRY-}helloworld_grain:${GRAIN_VER_HELLOWORLD:-latest}
    volumes:
      - helloworld_grain_volume:/app_grain:ro

  myreminder_grain:
    image: ${DOCKER_REGISTRY-}myreminder_grain:${GRAIN_VER_MYREMINDER:-latest}
    volumes:
      - myreminder_grain_volume:/app_grain:ro

  webclientdemo:
    image: ${DOCKER_REGISTRY-}webclientdemo:${WEB_CLIENT_VER:-latest}
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=${HTTPS_PORT:-443}
      - Kestrel__Certificates__Default__Path=/root/.dotnet/https/demo-cert.pfx
      - Kestrel__Certificates__Default__Password=${SSL_PASS}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - type: bind
        source: ./ssl_cert/
        target: /root/.dotnet/https/
        read_only: true
    networks:
      - orleans_virtual_network
    depends_on: 
      - console_silohost
      - demo_mongo_store

  demo_mongo_store:
    image: mongo:4
    volumes:
      - demo_mongo_db_volume:/data/db
    networks:
      - orleans_virtual_network

networks:
  orleans_virtual_network:

volumes:
  helloworld_grain_volume:
  myreminder_grain_volume:
  demo_mongo_db_volume:
