version: '3.7'

services: 
  localconsolesilohost:
    image: ${DOCKER_REGISTRY-}localconsolesilohost:${SILO_HOST_VER:-latest}
    environment:
      - ORLEANS_HOST_APP_Orleans__SiloConfig__AdvertisedIp=172.30.0.3
      - GrainLoadPath=/grains
      - ORLEANS_HOST_APP_Orleans__GrainOption__LoadPaths__0={GrainLoadPath}/helloworld_grain/HelloWorld.Grain.dll
      - ORLEANS_HOST_APP_Orleans__GrainOption__LoadPaths__1={GrainLoadPath}/myreminder_grain/MyReminder.Grain.dll
    volumes:
      - helloworld_grain_volume:/grains/helloworld_grain
      - myreminder_grain_volume:/grains/myreminder_grain
    networks:
      orleans-internal:
        ipv4_address: 172.30.0.3
    depends_on:
      - helloworld_grain
      - myreminder_grain
      - demo_mongo_store

  helloworld_grain:
    image: ${DOCKER_REGISTRY-}helloworld_grain:${GRAIN_VER_HELLOWORLD:-latest}
    volumes:
      - helloworld_grain_volume:/app_grain

  myreminder_grain:
    image: ${DOCKER_REGISTRY-}myreminder_grain:${GRAIN_VER_MYREMINDER:-latest}
    volumes:
      - myreminder_grain_volume:/app_grain

  webclientdemo:
    image: ${DOCKER_REGISTRY-}webclientdemo:${WEB_CLIENT_VER:-latest}
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=${HTTPS_PORT:-443}
      - Kestrel__Certificates__Default__Path=/root/.dotnet/https/demo-cert.pfx
      - Kestrel__Certificates__Default__Password=${SSL_PASS}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./ssl_cert/:/root/.dotnet/https/:ro
    networks:
      orleans-internal:
        ipv4_address: 172.30.0.2
    depends_on: 
      - localconsolesilohost
      - demo_mongo_store

  demo_mongo_store:
    image: mongo:4
    volumes:
      - demo_mongo_db_volume:/data/db
    networks:
      orleans-internal:
        ipv4_address: 172.30.0.4

volumes:
  helloworld_grain_volume:
  myreminder_grain_volume:
  demo_mongo_db_volume:

networks:
  orleans-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
      